import { NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";
import { supabaseAdmin } from "@/lib/supabaseAdmin";

const resend = new Resend(process.env.RESEND_API_KEY);

type CaptureLeadBody = {
  email: string;
  companyName?: string;
  role?: string;
  teamSize?: number;
  auditId?: string;
  totalMonthlySavings: number;
  website?: string;
};

const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export async function POST(request: NextRequest) {
  try {
    const body = (await request.json()) as CaptureLeadBody;
    const {
      email,
      companyName,
      role,
      teamSize,
      auditId,
      totalMonthlySavings,
      website,
    } = body;

    if (!email || !EMAIL_REGEX.test(email)) {
      return NextResponse.json(
        { error: "Invalid email address" },
        { status: 400 },
      );
    }

    if (website && website.trim() !== "") {
      return NextResponse.json({ success: true });
    }

    let lead: { id: string } | null = null;

    const { data, error: dbError } = await supabaseAdmin
      .from("leads")
      .insert({
        email,
        company_name: companyName || null,
        role: role || null,
        team_size: teamSize ?? null,
        audit_id: auditId || null,
        total_monthly_savings: totalMonthlySavings,
      })
      .select()
      .single();

    if (dbError) {
      console.error("[capture-lead] Supabase insert failed:", dbError);
    } else {
      lead = data;
    }

    const annualSavings = totalMonthlySavings * 12;
    const appUrl = process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/, "");
    const auditUrl =
      auditId && appUrl ? `${appUrl}/audit/${auditId}` : null;

    try {
      await resend.emails.send({
        from: "SpendScope <onboarding@resend.dev>",
        to: email,
        subject: "Your AI Spend Audit Results",
        html: `
    <!DOCTYPE html>
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 600px; 
                 margin: 0 auto; padding: 40px 20px; background: #ffffff;">
      
      <h1 style="color: #1a1a2e; font-size: 28px; margin-bottom: 8px;">
        Your AI Spend Audit
      </h1>
      <p style="color: #666; margin-bottom: 32px;">
        Here's a summary of what we found.
      </p>
      
      <div style="background: #f0fdf4; border: 1px solid #16a34a; 
                  border-radius: 12px; padding: 24px; margin-bottom: 24px;">
        <p style="color: #15803d; font-size: 14px; 
                  text-transform: uppercase; margin: 0 0 8px;">
          Potential Monthly Savings
        </p>
        <p style="color: #14532d; font-size: 42px; 
                  font-weight: bold; margin: 0;">
          $${totalMonthlySavings.toLocaleString()}/mo
        </p>
        <p style="color: #16a34a; font-size: 18px; margin: 8px 0 0;">
          That's $${annualSavings.toLocaleString()} per year
        </p>
      </div>
      
      ${
        auditUrl
          ? `
      <div style="text-align: center; margin-bottom: 32px;">
        <a href="${auditUrl}" 
           style="background: #5b4fdb; color: white; padding: 14px 28px; 
                  border-radius: 8px; text-decoration: none; 
                  font-weight: bold; font-size: 16px;">
          View Your Full Audit Report →
        </a>
      </div>
      `
          : ""
      }
      
      ${
        totalMonthlySavings > 500
          ? `
      <div style="background: #fef3c7; border: 1px solid #d97706; 
                  border-radius: 12px; padding: 20px; margin-bottom: 24px;">
        <p style="color: #92400e; font-weight: bold; margin: 0 0 8px;">
          High Savings Detected
        </p>
        <p style="color: #78350f; margin: 0;">
          Your savings level qualifies for a complimentary Credex 
          consultation. A team member will reach out within 1 business day 
          to show you available discounted credits for your stack.
        </p>
      </div>
      `
          : ""
      }
      
      <p style="color: #999; font-size: 13px; margin-top: 40px;">
        This audit was generated by SpendScope, a free tool by Credex. 
        Credex offers discounted AI infrastructure credits from companies 
        that overforecast usage. Visit credex.rocks to learn more.
      </p>
      
    </body>
    </html>
  `,
      });
    } catch (emailError) {
      console.error("[capture-lead] Resend email failed:", emailError);
    }

    return NextResponse.json({
      success: true,
      leadId: lead?.id ?? null,
    });
  } catch (error) {
    console.error("[capture-lead] Request failed:", error);
    return NextResponse.json(
      { error: "Unable to process your request. Please try again." },
      { status: 500 },
    );
  }
}
